sudo: false
language: erlang
notifications:
  email: false
matrix:
  include:
  - otp_release: 17.5
    dist: trusty
  - otp_release: R16B03-1
    dist: trusty
  - otp_release: R15B03
    dist: trusty
