;;; typst-preview-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from typst-preview.el

(autoload 'typst-preview-mode "typst-preview" "\
Toggle typst-preview minor mode.

This is a minor mode.  If called interactively, toggle the
`typst-preview mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `typst-preview-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'typst-preview-start "typst-preview" "\
Start typst-preview server and connect current buffer.

If OPEN-BROWSER is set and non-NIL, then it will automatically
open a default browser window.

(fn &optional OPEN-BROWSER)" t)
(autoload 'typst-preview-connected-p "typst-preview" "\
Return t if websocket is connected to typst-preview server.")
(autoload 'typst-preview-stop "typst-preview" "\
Stop typst-preview buffer by killing websocket connection." t)
(autoload 'typst-preview-restart "typst-preview" "\
Restart typst-preview server." t)
(autoload 'typst-preview-send-position "typst-preview" "\
Send position in buffer to preview server." t)
(autoload 'typst-preview-open-browser "typst-preview" "\
Open typst-preview browser interactively." t)
(autoload 'typst-preview-list-active-files "typst-preview" "\
List active typst files." t)
(autoload 'typst-preview-clear-active-files "typst-preview" "\
Clear all active typst files." t)
(register-definition-prefixes "typst-preview" '("typst-preview-"))

;;; End of scraped data

(provide 'typst-preview-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; typst-preview-autoloads.el ends here
