;;; boxes-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from boxes.el

(autoload 'boxes-create "boxes" "\
Automagicly create a new box around the region based on the default type." t)
(autoload 'boxes-remove "boxes" "\
Automagicly remove a new box around the region based on the default type." t)
(autoload 'boxes-command-on-region "boxes" "\
Create or Remove boxes from a region.

To create a box select a region, hit \\[boxes-command-on-region]
& enter a box type.  Box type selection uses tab completion on
the supported types.

To remove a box simply prefix a 1 to the call, eg M-1
\\[boxes-command-on-region] will remove a box from a region.

Note that interactive use requires `boxes' >= 2.1.0 to support
querying the supported types.

When calling from Lisp, supply the region START & END and the box
TYPE to create a box.  Specifying a non-nil value for REMOVE,
removes the box.

(fn START END TYPE &optional REMOVE)" t)
(register-definition-prefixes "boxes" '("boxes-"))

;;; End of scraped data

(provide 'boxes-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; boxes-autoloads.el ends here
