;;; jwt-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from jwt.el

(autoload 'jwt-decode "jwt" "\
Decode TOKEN and display results in a buffer.

(fn TOKEN)" t)
(autoload 'jwt-decode-at-point "jwt" "\
Decode token at point and display results in a buffer." t)
(autoload 'jwt-decode-region "jwt" "\
Decode token in region START to END and display results in a buffer.

(fn START END)" t)
(register-definition-prefixes "jwt" '("jwt-"))

;;; End of scraped data

(provide 'jwt-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; jwt-autoloads.el ends here
