;;; 0xc-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from 0xc.el

(autoload '0xc-convert "0xc" "\
Read a number and a base, and output its representation in said base.
If SILENT is non-nil, do not output anything

(fn BASE &optional NUMBER SILENT)" t)
(autoload '0xc-convert-point "0xc" "\
Replace the number at point with its representation in base.

(fn &optional BASE)" t)
(register-definition-prefixes "0xc" '("0xc-"))


;;; Generated autoloads from 0xc-live.el

(autoload '0xc-live-convert "0xc-live" "\
Show all possible conversions of a number in another buffer as you type it." t)
(register-definition-prefixes "0xc-live" '("0xc-live-"))

;;; End of scraped data

(provide '0xc-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; 0xc-autoloads.el ends here
