;;; math-preview-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from math-preview.el

(autoload 'math-preview-start-process "math-preview" "\
Start math-preview process." t)
(autoload 'math-preview-stop-process "math-preview" "\
Stop math-preview process." t)
(autoload 'math-preview-region "math-preview" "\
Preview equations in region between `BEG' and `END'.

(fn BEG END)" t)
(autoload 'math-preview-all "math-preview" "\
Preview equations in buffer." t)
(autoload 'math-preview-at-point "math-preview" "\
Preview equations at point." t)
(autoload 'math-preview-clear-region "math-preview" "\
Remove all preview overlays in region between `BEG' and `END'.

(fn BEG END)" t)
(autoload 'math-preview-clear-at-point "math-preview" "\
Remove all preview overlays." t)
(autoload 'math-preview-clear-all "math-preview" "\
Remove all preview overlays." t)
(autoload 'math-preview-increment-scale "math-preview" "\
Increment image size.
Scale is changed by `N' times `math-preview-scale-increment'

(fn N)" t)
(autoload 'math-preview-decrement-scale "math-preview" "\
Decrement image size.
Scale is changed by `N' times `math-preview-scale-increment'

(fn N)" t)
(autoload 'math-preview-copy-svg "math-preview" "\
Copy SVG image to clipboard." t)
(autoload 'math-preview-reset-numbering "math-preview" "\
Reset MathJax equation numbering from `NUM'.

(fn NUM)" t)
(register-definition-prefixes "math-preview" '("math-preview-"))

;;; End of scraped data

(provide 'math-preview-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; math-preview-autoloads.el ends here
