;;; go-gen-test-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from go-gen-test.el

(autoload 'go-gen-test-dwim "go-gen-test" "\
Generate tests for functions you want to.
If you call this function while region is active it extracts
functions defined between START and END and generate tests for it.
Else it generates tests for exported or all functions.
You can customize this behavior with `go-gen-test-default-functions'.

(fn &optional START END)" t)
(autoload 'go-gen-test-all "go-gen-test" "\
Generate tests for all functions." t)
(autoload 'go-gen-test-exported "go-gen-test" "\
Generate tests for all exported functions." t)
(register-definition-prefixes "go-gen-test" '("go-gen-test-"))

;;; End of scraped data

(provide 'go-gen-test-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; go-gen-test-autoloads.el ends here
