;;; sed-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from sed-mode.el

 (add-to-list 'auto-mode-alist '("\\.sed\\'" . sed-mode))
 (add-to-list 'interpreter-mode-alist '("sed" . sed-mode))
(autoload 'sed-mode "sed-mode" "\
Sed editing mode.

(fn)" t)
(register-definition-prefixes "sed-mode" '("sed-"))

;;; End of scraped data

(provide 'sed-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; sed-mode-autoloads.el ends here
