;;; pomo-cat-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from pomo-cat.el

(autoload 'pomo-cat-start "pomo-cat" "\
Start the Pomodoro timer." t)
(autoload 'pomo-cat-stop "pomo-cat" "\
Stop the Pomodoro timer and clear cat display." t)
(autoload 'pomo-cat-delay-break "pomo-cat" "\
Delay the current break for SECONDS.

(fn &optional SECONDS)" t)
(autoload 'pomo-cat-stop-break "pomo-cat" "\
Simply stop the current break period as if it has finished." t)
(register-definition-prefixes "pomo-cat" '("pomo-cat-"))

;;; End of scraped data

(provide 'pomo-cat-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; pomo-cat-autoloads.el ends here
