;;; sequential-yank-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from sequential-yank.el

(defvar sequential-yank-mode nil "\
Non-nil if Sequential-Yank mode is enabled.
See the `sequential-yank-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `sequential-yank-mode'.")
(custom-autoload 'sequential-yank-mode "sequential-yank" nil)
(autoload 'sequential-yank-mode "sequential-yank" "\
Toggle sequential yank mode.

With a non-nil list argument (\\[universal-argument]), the sequential yank queue
is initialized with the last string of `kill-ring'.

With a numeric argument, the sequential yank queue is initialized
with the last ARG strings of `kill-ring'.

Otherwise, the sequential yank queue is initialized with an empty list.

(fn &optional ARG)" t)
(register-definition-prefixes "sequential-yank" '("sequential-yank"))

;;; End of scraped data

(provide 'sequential-yank-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; sequential-yank-autoloads.el ends here
