;;; kql-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from kql-mode.el

(autoload 'kql-mode "kql-mode" "\
Major mode for highlighting Kusto Query Language (KQL) files.

(fn)" t)
(register-definition-prefixes "kql-mode" '("kql-"))

;;; End of scraped data

(provide 'kql-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; kql-mode-autoloads.el ends here
