;;; easy-theme-preview-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from easy-theme-preview.el

(autoload 'easy-theme-preview "easy-theme-preview" "\
Open a buffer listing all available themes for preview." t)
(register-definition-prefixes "easy-theme-preview" '("easy-theme-preview-"))

;;; End of scraped data

(provide 'easy-theme-preview-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; easy-theme-preview-autoloads.el ends here
