;;; dired-video-thumbnail-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from dired-video-thumbnail.el

(autoload 'dired-video-thumbnail "dired-video-thumbnail" "\
Display thumbnails for video files in current dired buffer.
If files are marked, show thumbnails for marked videos only.
Otherwise, show thumbnails for all videos in the directory.
With prefix argument RECURSIVE, include videos from subdirectories.

When `dired-video-thumbnail-auto-recursive' is non-nil and the current
directory has no video files but has subdirectories, recursive mode
is automatically enabled.

(fn &optional RECURSIVE)" t)
(autoload 'dired-video-thumbnail-recursive "dired-video-thumbnail" "\
Display thumbnails for video files recursively from current directory." t)
(register-definition-prefixes "dired-video-thumbnail" '("dired-video-thumbnail-"))


;;; Generated autoloads from dired-video-thumbnail-transient.el

(autoload 'dired-video-thumbnail-transient "dired-video-thumbnail-transient" "\
Transient menu for dired-video-thumbnail.

(fn)" t)
(autoload 'dired-video-thumbnail-transient-setup-keys "dired-video-thumbnail-transient" "\
Set up keybindings for the transient menu.")
(register-definition-prefixes "dired-video-thumbnail-transient" '("dired-video-thumbnail-transient--state-description"))

;;; End of scraped data

(provide 'dired-video-thumbnail-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; dired-video-thumbnail-autoloads.el ends here
