;;; ascii-table-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ascii-table.el

(autoload 'ascii-table "ascii-table" "\
Show an interactive ASCII table in the other window." t)
(register-definition-prefixes "ascii-table" '("ascii-table-"))

;;; End of scraped data

(provide 'ascii-table-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ascii-table-autoloads.el ends here
