;;; magit-diff-flycheck-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from magit-diff-flycheck.el

(autoload 'magit-diff-flycheck "magit-diff-flycheck" "\
Run flycheck for SCOPE in `magit-diff-mode'.

(fn &optional SCOPE)" t)
(register-definition-prefixes "magit-diff-flycheck" '("magit-diff-flycheck-"))

;;; End of scraped data

(provide 'magit-diff-flycheck-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; magit-diff-flycheck-autoloads.el ends here
