;;; magit-commit-mark-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from magit-commit-mark.el

(autoload 'magit-commit-mark-toggle-read "magit-commit-mark" "\
Toggle the commit at point read status." t)
(function-put 'magit-commit-mark-toggle-read 'important-return-value 'nil)
(autoload 'magit-commit-mark-toggle-star "magit-commit-mark" "\
Toggle the commit at point star status." t)
(function-put 'magit-commit-mark-toggle-star 'important-return-value 'nil)
(autoload 'magit-commit-mark-toggle-urgent "magit-commit-mark" "\
Toggle the commit at point urgent status." t)
(function-put 'magit-commit-mark-toggle-urgent 'important-return-value 'nil)
(autoload 'magit-commit-mark-next-unread "magit-commit-mark" "\
Jump to the next unread commit." t)
(function-put 'magit-commit-mark-next-unread 'important-return-value 'nil)
(autoload 'magit-commit-mark-prev-unread "magit-commit-mark" "\
Jump to the previous unread commit." t)
(function-put 'magit-commit-mark-prev-unread 'important-return-value 'nil)
(autoload 'magit-commit-mark-report-urgent "magit-commit-mark" "\
Report all urgent commits in the region or buffer." t)
(function-put 'magit-commit-mark-report-urgent 'important-return-value 'nil)
(autoload 'magit-commit-mark-report-star "magit-commit-mark" "\
Report all starred commits in the region or buffer." t)
(function-put 'magit-commit-mark-report-star 'important-return-value 'nil)
(autoload 'magit-commit-mark-mode "magit-commit-mark" "\
Minor mode for marking commits as read/unread in Magit log buffers.

When enabled, commits are visually distinguished by their read status
and can be marked as read, starred, or urgent.  The state is persisted
between sessions.

This is a minor mode.  If called interactively, toggle the
`Magit-Commit-Mark mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `magit-commit-mark-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "magit-commit-mark" '("magit-commit-mark-"))

;;; End of scraped data

(provide 'magit-commit-mark-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; magit-commit-mark-autoloads.el ends here
