;;; visual-shorthands-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from visual-shorthands.el

(autoload 'visual-shorthands-mode "visual-shorthands" "\
Toggle visual shorthand overlays with auto-reveal in current buffer.

When enabled, long symbol prefixes defined in
`visual-shorthands-alist' are visually replaced with shorter
alternatives using overlays with the `invisible' property.

Symbols are automatically revealed when the cursor enters them,
allowing normal character-by-character navigation through the
actual buffer text.

This is a minor mode.  If called interactively, toggle the
`Visual-Shorthands mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `visual-shorthands-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'visual-shorthands-add-mapping "visual-shorthands" "\
Add visual shorthand mapping from LONGHAND to SHORTHAND.

When called interactively, dynamically highlights symbols in buffer
matching LONGHAND as you type.  Highlighting uses
`visual-shorthands-preview-face' to show which prefix portions will
be hidden.

LONGHAND is the full prefix to replace.
SHORTHAND is the visual replacement.

Updates `visual-shorthands-alist' by adding or replacing mapping.
Mappings are sorted by descending LONGHAND length for correct matching.

If `visual-shorthands-mode' is active, immediately applies overlays
to all matching symbols.

Also see `visual-shorthands-remove-mapping' `visual-shorthands-clear-mappings'.

(fn LONGHAND SHORTHAND)" t)
(autoload 'visual-shorthands-remove-mapping "visual-shorthands" "\
Remove visual shorthand mapping for LONGHAND.

(fn LONGHAND)" t)
(autoload 'visual-shorthands-clear-mappings "visual-shorthands" "\
Clear all visual shorthand mappings." t)
(autoload 'visual-shorthands-setup "visual-shorthands" "\
Set up visual shorthands with MAPPINGS and enable mode.

(fn MAPPINGS)")
(register-definition-prefixes "visual-shorthands" '("visual-shorthands-"))

;;; End of scraped data

(provide 'visual-shorthands-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; visual-shorthands-autoloads.el ends here
