;;; uniline-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from uniline-core.el

(register-definition-prefixes "uniline-core" '("uniline-"))


;;; Generated autoloads from uniline-transient.el

(register-definition-prefixes "uniline-transient" '("uniline-"))

;;; End of scraped data

(provide 'uniline-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; uniline-autoloads.el ends here
