;;; rg-themes-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from rg-themes.el

(autoload 'rg-themes-set "rg-themes" "\
Set the current theme to THEME.

By default, this function disables all loaded themes before
applying the new one. The argument DONT-DISABLE-REST, when non
nil, inhibits this behaviour.

(fn THEME &optional DONT-DISABLE-REST)" t)
(and load-file-name (boundp 'custom-theme-load-path) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "rg-themes" '("rg-themes"))


;;; Generated autoloads from rg-themes-bosque-theme.el

(register-definition-prefixes "rg-themes-bosque-theme" '("rg-themes-bosque"))


;;; Generated autoloads from rg-themes-cappuccino-noir-theme.el

(register-definition-prefixes "rg-themes-cappuccino-noir-theme" '("rg-themes-cappuccino-noir"))


;;; Generated autoloads from rg-themes-ellas-theme.el

(register-definition-prefixes "rg-themes-ellas-theme" '("rg-themes-ellas"))


;;; Generated autoloads from rg-themes-purpurina-theme.el

(register-definition-prefixes "rg-themes-purpurina-theme" '("rg-themes-purpurina"))


;;; Generated autoloads from rg-themes-somnus-theme.el

(register-definition-prefixes "rg-themes-somnus-theme" '("rg-themes-somnus"))

;;; End of scraped data

(provide 'rg-themes-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; rg-themes-autoloads.el ends here
