;;; dtext-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from dtext-mode.el

(autoload 'dtext-mode "dtext-mode" "\
Major mode for writing Danbooru's DText markup.

\\{dtext-mode-map}

(fn)" t)
(autoload 'dtext-scratch "dtext-mode" "\
Open *dtext-scratch* buffer to quickly edit DText posts." t)
(add-to-list 'auto-mode-alist '("\\.dtext\\'" . dtext-mode))
(register-definition-prefixes "dtext-mode" '("dtext-"))

;;; End of scraped data

(provide 'dtext-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; dtext-mode-autoloads.el ends here
