;;; cider-decompile-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from cider-decompile.el

(autoload 'cider-decompile-func "cider-decompile" "\
Asks for the func name (FN-NAME) in the current namespace.and decompiles." t)
(autoload 'cider-decompile-ns-func "cider-decompile" "\
Asks for the func name (FN-NAME) in a specific namespace and decompiles it.
The FN-NAME should be prefixed with the namespace.

(fn FN-NAME)" t)
(register-definition-prefixes "cider-decompile" '("cider-decompile"))

;;; End of scraped data

(provide 'cider-decompile-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; cider-decompile-autoloads.el ends here
